name: Version Gate

on:
  pull_request:
    branches:
      - "release-**"
    paths:
      - "release.yaml"

permissions:
  contents: read

jobs:
  validate-release-yaml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5

      - uses: ./.github/actions/install-yq

      - name: Validate release.yaml
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          .github/scripts/validate-release-yaml.sh "${{ github.base_ref }}" "Kuadrant"